### ISSUE TITLE
❤ your screenshots....

### ISSUE THREAD

**Issue by PySimpleGUI** [sampconrad/busca-diario#1]
Thank you so much for posting screenshots of your application and for the story you posted on LinkedIn ![image](https://github.com/sampconrad/busca-diario/assets/46163555/8a310495-328c-41c9-853e-f0d6e85d13da)

Nothing more exciting than seeing someone excited about programming after using PySimpleGUI. 

✅  FUN
✅  Success

I think you managed to check both the boxes.  Mission accomplished!

**Comment by sampconrad** [comment]
Thank you!
I'm a web & mobile dev and I don't usually dip my toes into Python land but your package made it very easy and pain-free to build a GUI. Will most definitely be using it on future projects!

**Comment by PySimpleGUI** [comment]
We'll visit your land next... thanks for the kind words and support!
